# 从各个文件导入节点映射
from .nodes.random_number_node import NODE_CLASS_MAPPINGS as RANDOM_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as RANDOM_DISPLAY_NAME_MAPPINGS
from .smart_display_node import NODE_CLASS_MAPPINGS as SMART_DISPLAY_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SMART_DISPLAY_DISPLAY_NAME_MAPPINGS

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {
    **RANDOM_NODE_MAPPINGS,
    **SMART_DISPLAY_NODE_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **RANDOM_DISPLAY_NAME_MAPPINGS,
    **SMART_DISPLAY_DISPLAY_NAME_MAPPINGS
}

WEB_DIRECTORY = "./web/extensions"
__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']