# 从各个文件导入节点映射
from .nodes.random_number_node import NODE_CLASS_MAPPINGS as RANDOM_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as RANDOM_DISPLAY_NAME_MAPPINGS
from .nodes.smart_display_node import NODE_CLASS_MAPPINGS as SMART_DISPLAY_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SMART_DISPLAY_DISPLAY_NAME_MAPPINGS
from .nodes.prompt_edit_node import NODE_CLASS_MAPPINGS as PROMPT_EDIT_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PROMPT_EDIT_NODE_DISPLAY_NAMES
from .nodes.prompt_node import NODE_CLASS_MAPPINGS as PROMPT_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PROMPT_NODE_DISPLAY_NAMES
from .nodes.theme_prompt_node import NODE_CLASS_MAPPINGS as THEME_PROMPT_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as THEME_PROMPT_NODE_DISPLAY_NAMES
from .nodes.qwen_size_preset import NODE_CLASS_MAPPINGS as QWEN_SIZE_PRESET_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as QWEN_SIZE_PRESET_DISPLAY_NAMES
from .nodes.qwen_light_preset import NODE_CLASS_MAPPINGS as QWEN_LIGHT_PRESET_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as QWEN_LIGHT_PRESET_DISPLAY_NAMES
from .nodes.qwen_bloom_effect import NODE_CLASS_MAPPINGS as QWEN_BLOOM_EFFECT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as QWEN_BLOOM_EFFECT_DISPLAY_NAMES
from .nodes.qwen_camera_preset import NODE_CLASS_MAPPINGS as QWEN_CAMERA_PRESET_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as QWEN_CAMERA_PRESET_DISPLAY_NAMES
from .nodes.qwen_grain_effect import NODE_CLASS_MAPPINGS as QWEN_GRAIN_EFFECT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as QWEN_GRAIN_EFFECT_DISPLAY_NAMES
from .nodes.batch_size_control_node import NODE_CLASS_MAPPINGS as BATCH_SIZE_CONTROL_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BATCH_SIZE_CONTROL_DISPLAY_NAMES
from .nodes.shutdown_timer_node import NODE_CLASS_MAPPINGS as SHUTDOWN_TIMER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SHUTDOWN_TIMER_DISPLAY_NAMES
from .nodes.shutdown_timer_advanced_node import NODE_CLASS_MAPPINGS as SHUTDOWN_TIMER_ADVANCED_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SHUTDOWN_TIMER_ADVANCED_DISPLAY_NAMES

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {
    **RANDOM_NODE_MAPPINGS,
    **SMART_DISPLAY_NODE_MAPPINGS,
    **PROMPT_EDIT_NODE_MAPPINGS,
    **PROMPT_NODE_MAPPINGS,
    **THEME_PROMPT_NODE_MAPPINGS,
    **QWEN_SIZE_PRESET_MAPPINGS,
    **QWEN_LIGHT_PRESET_MAPPINGS,
    **QWEN_BLOOM_EFFECT_MAPPINGS,
    **QWEN_CAMERA_PRESET_MAPPINGS,
    **QWEN_GRAIN_EFFECT_MAPPINGS,
    **BATCH_SIZE_CONTROL_MAPPINGS,
    **SHUTDOWN_TIMER_MAPPINGS,
    **SHUTDOWN_TIMER_ADVANCED_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **RANDOM_DISPLAY_NAME_MAPPINGS,
    **SMART_DISPLAY_DISPLAY_NAME_MAPPINGS,
    **PROMPT_EDIT_NODE_DISPLAY_NAMES,
    **PROMPT_NODE_DISPLAY_NAMES,
    **THEME_PROMPT_NODE_DISPLAY_NAMES,
    **QWEN_SIZE_PRESET_DISPLAY_NAMES,
    **QWEN_LIGHT_PRESET_DISPLAY_NAMES,
    **QWEN_BLOOM_EFFECT_DISPLAY_NAMES,
    **QWEN_CAMERA_PRESET_DISPLAY_NAMES,
    **QWEN_GRAIN_EFFECT_DISPLAY_NAMES,
    **BATCH_SIZE_CONTROL_DISPLAY_NAMES,
    **SHUTDOWN_TIMER_DISPLAY_NAMES,
    **SHUTDOWN_TIMER_ADVANCED_DISPLAY_NAMES
}

WEB_DIRECTORY = "./web/extensions"
__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']